package com.epam.prihodko.finaltask.controller;

public enum CommandName {
    LOGIN,
    LOGOUT,
    SIGNUP,
    UPDATE,
    UPDATE_ORDER,
    REMOVE_ORDER,
    FIND_APARTMENT,
    CHANGE,
    GO_TO_CHANGE_ORDER_PAGE,
    GO_TO_REGISTR_PAGE,
    GO_TO_APARTMENTTABLE_PAGE,
    GO_TO_USER_PERSONAL_DATA_PAGE,
    GO_TO_MAKE_AN_ORDER_PAGE,
    MAKE_AN_ORDER,
    PREVIOUS_PAGE,
    TO_RESERVE_APARTMENT
}
